services:
  postgres:
    image: postgres:17
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}

  prestart:
    image: liquibase/liquibase:4.31
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    volumes:
      - ./liquibase/migrations:/liquibase/migrations
      - ./liquibase/changelog.xml:/liquibase/changelog.xml
      - ./liquibase/liquibase.properties:/liquibase/liquibase.properties
    command:
      - --defaults-file=/liquibase/liquibase.properties
      - update

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres

  api:
    image: '${DOCKER_IMAGE_API?Variable not set}:${TAG-latest}'
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      prestart:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN}
      - ENVIRONMENT=${ENVIRONMENT}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}


  otel-collector:
    image: otel/opentelemetry-collector:0.126.0
    volumes:
      - ./observability/otel-collector-config.yml:/etc/otelcol/config.yaml

  prometheus:
    image: prom/prometheus:v3.3.1
    volumes:
      - ./observability/prometheus.yml:/workspace/prometheus.yml
    command:
      - --config.file=/workspace/prometheus.yml
      - --enable-feature=exemplar-storage

  tempo:
    image: grafana/tempo:2.7.2
    volumes:
      - ./observability/tempo.yml:/etc/tempo.yml
    command: [ "-config.file=/etc/tempo.yml", "--target=all", "--storage.trace.backend=local", "--storage.trace.local.path=/var/tempo", "--auth.enabled=false" ]

  loki:
    image: grafana/loki:3.5.0
    volumes:
      - ./observability/loki-config.yml:/etc/loki/local-config.yml
    command: -config.file=/etc/loki/local-config.yml

  grafana:
    image: grafana/grafana:12.0.1
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_FEATURE_TOGGLES_ENABLE=accessControlOnCall
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app
    ports:
      - 3000:3000/tcp
    volumes:
      - ./observability/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./observability/grafana/plugins:/etc/grafana/provisioning/plugins
      - ./observability/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./observability/grafana/dashboards:/etc/grafana/dashboards

  mkdocs:
    image: squidfunk/mkdocs-material:9.6
    ports:
      - "8081:8000"
    volumes:
      - .:/docs

volumes:
  postgres-data:
