services:

  postgres:
    restart: "no"
    ports:
      - "5432:5432"

  adminer:
    restart: "no"
    ports:
      - "8080:8080"

  api:
    restart: "no"
    ports:
      - "8000:8000"
    build:
      context: ./api
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    develop:
      watch:
        - path: ./api/src
          action: sync
          target: /app/app
          ignore:
            - ./api/.venv
            - .venv
        - path: ./api/pyproject.toml
          action: rebuild

  otel-collector:
    restart: "no"
    ports:
      - "8889:8889" # metrics endpoint

  prometheus:
    restart: "no"
    ports:
      - "9090:9090"

  tempo:
    restart: "no"
    ports:
      - "3200:3200"

  loki:
    restart: "no"
    ports:
      - "3100:3100"

  grafana:
    restart: "no"
    ports:
      - 3000:3000/tcp
