receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
  debug:
    verbosity: detailed

  prometheus:
    endpoint: 0.0.0.0:8889
    # namespace: default

  otlphttp/tempo:
    endpoint: http://tempo:4318

  otlphttp/loki:
    endpoint: http://loki:3100/otlp

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug,otlphttp/tempo]
    metrics:
      receivers: [otlp]
      exporters: [debug,prometheus]
    logs:
      receivers: [otlp]
      exporters: [debug,otlphttp/loki]
