[project]
name = "lloyd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "psycopg[binary]>=3.2.8",
    "pydantic>=2.11.4",
]

[dependency-groups]
dev = [
    "ruff>=0.11.9",
]
