site_name: Lloyd
theme:
  name: 'material'
  icon:
    logo: material/glass-cocktail
  favicon: images/favicon.svg
  palette:
      # Palette toggle for light mode
      - scheme: default
        primary: red
        accent: orange
        toggle:
          icon: material/brightness-4
          name: Switch to dark mode

      # Palette toggle for dark mode
      - scheme: slate
        primary: red
        accent: orange
        toggle:
          icon: material/brightness-7
          name: Switch to light mode
plugins:
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
